export const APPLICATION_SEEDS = [
  {
    studentEmail: "student.a@kaushalsetu.demo",
    companyEmail: "industry.abc@kaushalsetu.demo",
    opportunityTitle: "Full Stack Developer Intern",
    status: "UNDER_REVIEW",
    coverLetter:
      "I have built React and Node.js projects at college and would like to contribute to your internship.",
    appliedAt: "2026-09-02T08:30:00.000Z",
  },
  {
    studentEmail: "student.c@kaushalsetu.demo",
    companyEmail: "industry.abc@kaushalsetu.demo",
    opportunityTitle: "Full Stack Developer Intern",
    status: "APPLIED",
    coverLetter: "I meet the core web stack requirements and am available for a six-month internship.",
    appliedAt: "2026-09-04T10:00:00.000Z",
  },
  {
    studentEmail: "student.b@kaushalsetu.demo",
    companyEmail: "industry.abc@kaushalsetu.demo",
    opportunityTitle: "Full Stack Developer Intern",
    status: "APPLIED",
    coverLetter: "I am expanding from Java into full-stack web development and would value this internship.",
    appliedAt: "2026-09-05T09:15:00.000Z",
  },
  {
    studentEmail: "student.a@kaushalsetu.demo",
    companyEmail: "industry.abc@kaushalsetu.demo",
    opportunityTitle: "Frontend Developer Intern",
    status: "SHORTLISTED",
    coverLetter: "My strongest work is in React, HTML, and CSS. I would like to join the frontend internship.",
    appliedAt: "2026-09-03T07:00:00.000Z",
  },
  {
    studentEmail: "student.c@kaushalsetu.demo",
    companyEmail: "industry.abc@kaushalsetu.demo",
    opportunityTitle: "Frontend Developer Intern",
    status: "APPLIED",
    coverLetter: "I can contribute to dashboard UI work with React and Tailwind CSS.",
    appliedAt: "2026-09-06T11:20:00.000Z",
  },
  {
    studentEmail: "student.b@kaushalsetu.demo",
    companyEmail: "industry.abc@kaushalsetu.demo",
    opportunityTitle: "Frontend Developer Intern",
    status: "WITHDRAWN",
    coverLetter: "Withdrawn after focusing on Java backend roles.",
    appliedAt: "2026-09-04T12:00:00.000Z",
  },
  {
    studentEmail: "student.b@kaushalsetu.demo",
    companyEmail: "industry.nova@kaushalsetu.demo",
    opportunityTitle: "Java Backend Developer Intern",
    status: "UNDER_REVIEW",
    coverLetter: "I have Java, SQL, and REST API coursework and personal projects aligned with this role.",
    appliedAt: "2026-09-03T09:00:00.000Z",
  },
  {
    studentEmail: "student.a@kaushalsetu.demo",
    companyEmail: "industry.nova@kaushalsetu.demo",
    opportunityTitle: "Java Backend Developer Intern",
    status: "APPLIED",
    coverLetter: "I am applying to broaden backend experience alongside my JavaScript work.",
    appliedAt: "2026-09-05T14:00:00.000Z",
  },
];
