export const ASSESSMENTS = [
  {
    title: "Full Stack Development Assessment",
    description:
      "Evaluates JavaScript, React, Node.js, SQL, and Git against industry-relevant full-stack tasks.",
    questions: [
      {
        skill: "JavaScript",
        difficulty: "EASY",
        questionText: "What does Array.prototype.map() return?",
        options: [
          "The original array, mutated",
          "A new array with the results of calling a function on every element",
          "The first matching element",
          "A boolean indicating whether every element passed",
        ],
        correctIndex: 1,
      },
      {
        skill: "JavaScript",
        difficulty: "MEDIUM",
        questionText: "Which comparison is true in JavaScript?",
        options: ["null == undefined", "null === undefined", "NaN === NaN", "[] === []"],
        correctIndex: 0,
      },
      {
        skill: "JavaScript",
        difficulty: "MEDIUM",
        questionText: "What is the purpose of Promise.all()?",
        options: [
          "Race the first promise to settle",
          "Wait until every promise fulfills, or reject if any reject",
          "Retry a promise until it succeeds",
          "Cancel all pending promises",
        ],
        correctIndex: 1,
      },
      {
        skill: "JavaScript",
        difficulty: "HARD",
        questionText: "In the event loop, when do microtasks (e.g. Promise.then) run relative to setTimeout(fn, 0)?",
        options: [
          "After the next macrotask, including the timeout",
          "Before the next macrotask, after the current call stack clears",
          "Only after I/O callbacks",
          "In a separate OS thread",
        ],
        correctIndex: 1,
      },
      {
        skill: "React",
        difficulty: "EASY",
        questionText: "What is the correct way to update state that depends on the previous value?",
        options: [
          "setCount(count + 1) always",
          "setCount((prev) => prev + 1)",
          "count++ inside the component body",
          "this.state.count += 1",
        ],
        correctIndex: 1,
      },
      {
        skill: "React",
        difficulty: "MEDIUM",
        questionText: "When should you include a value in a useEffect dependency array?",
        options: [
          "Never; empty arrays are always best",
          "Whenever the effect reads that value from props or state",
          "Only for functions",
          "Only for primitive numbers",
        ],
        correctIndex: 1,
      },
      {
        skill: "React",
        difficulty: "MEDIUM",
        questionText: "Why are keys required when rendering a list of components?",
        options: [
          "They style list items",
          "They help React identify which items changed, were added, or removed",
          "They replace the need for unique IDs in the database",
          "They disable re-renders",
        ],
        correctIndex: 1,
      },
      {
        skill: "React",
        difficulty: "HARD",
        questionText: "What does lifting state up solve?",
        options: [
          "Sharing state between sibling components via a common parent",
          "Persisting state to localStorage automatically",
          "Avoiding props entirely",
          "Making all state global by default",
        ],
        correctIndex: 0,
      },
      {
        skill: "Node.js",
        difficulty: "EASY",
        questionText: "What is the default module system traditionally used in Node.js (CommonJS)?",
        options: ["import/export only", "require and module.exports", "AMD define()", "SystemJS"],
        correctIndex: 1,
      },
      {
        skill: "Node.js",
        difficulty: "MEDIUM",
        questionText: "Why can a long CPU loop block other HTTP requests in a typical Node.js process?",
        options: [
          "Node uses one thread for JavaScript execution (event loop)",
          "HTTP is not supported",
          "Each request waits on a global mutex in the OS kernel only",
          "JavaScript cannot do I/O",
        ],
        correctIndex: 0,
      },
      {
        skill: "Node.js",
        difficulty: "MEDIUM",
        questionText: "In Express, where should you put JSON body parsing for POST /api routes?",
        options: [
          "express.json() middleware before those routes",
          "Only inside each controller after the response is sent",
          "In the browser",
          "Prisma schema",
        ],
        correctIndex: 0,
      },
      {
        skill: "Node.js",
        difficulty: "HARD",
        questionText: "What does process.nextTick() do compared to setImmediate()?",
        options: [
          "nextTick queues a function to run before the next event-loop phase; setImmediate runs on the check phase",
          "They are identical aliases",
          "setImmediate always runs first",
          "nextTick runs on a worker thread",
        ],
        correctIndex: 0,
      },
      {
        skill: "SQL",
        difficulty: "EASY",
        questionText: "Which clause filters rows after grouping in SQL?",
        options: ["WHERE", "HAVING", "FROM", "JOIN"],
        correctIndex: 1,
      },
      {
        skill: "SQL",
        difficulty: "MEDIUM",
        questionText: "What does an INNER JOIN return?",
        options: [
          "All rows from the left table even without matches",
          "Only rows that have matching values in both tables",
          "The Cartesian product only",
          "Distinct column names",
        ],
        correctIndex: 1,
      },
      {
        skill: "SQL",
        difficulty: "MEDIUM",
        questionText: "Which statement is true about a PRIMARY KEY?",
        options: [
          "It may contain duplicate NULLs",
          "It uniquely identifies rows and cannot be NULL",
          "A table can have several primary keys",
          "It is the same as an index on every column",
        ],
        correctIndex: 1,
      },
      {
        skill: "SQL",
        difficulty: "HARD",
        questionText: "What is a typical reason to use a transaction?",
        options: [
          "To skip indexes",
          "To apply several writes atomically (all succeed or all roll back)",
          "To make SELECT faster only",
          "To disable foreign keys permanently",
        ],
        correctIndex: 1,
      },
      {
        skill: "Git",
        difficulty: "EASY",
        questionText: "What does git clone do?",
        options: [
          "Deletes the remote repository",
          "Copies a remote repository to your machine",
          "Creates an empty commit",
          "Merges two branches",
        ],
        correctIndex: 1,
      },
      {
        skill: "Git",
        difficulty: "MEDIUM",
        questionText: "What is the difference between git merge and git rebase in typical use?",
        options: [
          "merge replays your commits on top of another branch; rebase creates a merge commit",
          "rebase replays commits onto another base; merge joins histories with a merge commit (usually)",
          "They produce identical commit graphs always",
          "rebase only works on tags",
        ],
        correctIndex: 1,
      },
      {
        skill: "Git",
        difficulty: "MEDIUM",
        questionText: "Which command stages all modified tracked files?",
        options: ["git commit -a --no-add", "git add -u", "git stash drop", "git reset --hard ORIG_HEAD"],
        correctIndex: 1,
      },
      {
        skill: "Git",
        difficulty: "HARD",
        questionText: "What does a detached HEAD state mean?",
        options: [
          "HEAD points at a commit, not a branch name",
          "The repository has no remotes",
          "The index is locked",
          "Git credentials expired",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    title: "Software Engineering Fundamentals",
    description:
      "Evaluates DSA, JavaScript, SQL, Git, and communication against core software-engineering practice.",
    questions: [
      {
        skill: "DSA",
        difficulty: "EASY",
        questionText: "What is the average-case time complexity of binary search on a sorted array?",
        options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
        correctIndex: 1,
      },
      {
        skill: "DSA",
        difficulty: "MEDIUM",
        questionText: "Which data structure is typically used for BFS in a graph?",
        options: ["Stack", "Queue", "Min-heap only", "Hash set only"],
        correctIndex: 1,
      },
      {
        skill: "DSA",
        difficulty: "MEDIUM",
        questionText: "What is the worst-case time complexity of inserting into an unbalanced binary search tree?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
        correctIndex: 2,
      },
      {
        skill: "DSA",
        difficulty: "HARD",
        questionText: "Which statement about hash tables is most accurate?",
        options: [
          "Lookup is always O(1) even with all keys colliding",
          "Expected lookup is O(1) with a good hash and load factor; collisions can degrade it",
          "They keep keys in sorted order",
          "They cannot store strings",
        ],
        correctIndex: 1,
      },
      {
        skill: "JavaScript",
        difficulty: "EASY",
        questionText: "Which keyword declares a block-scoped variable that cannot be reassigned?",
        options: ["var", "let", "const", "static"],
        correctIndex: 2,
      },
      {
        skill: "JavaScript",
        difficulty: "MEDIUM",
        questionText: "What does JSON.stringify({ a: undefined, b: 1 }) produce?",
        options: ['{"a":null,"b":1}', '{"b":1}', '{"a":undefined,"b":1}', "throws"],
        correctIndex: 1,
      },
      {
        skill: "JavaScript",
        difficulty: "MEDIUM",
        questionText: "How do you copy an array without mutating the original?",
        options: ["original.push", "original.splice(0)", "[...original] or original.slice()", "original = []"],
        correctIndex: 2,
      },
      {
        skill: "JavaScript",
        difficulty: "HARD",
        questionText: "What is a closure?",
        options: [
          "A function bundled with its lexical environment, retaining access to outer variables",
          "A way to close HTTP connections",
          "A class that cannot be extended",
          "A Git merge strategy",
        ],
        correctIndex: 0,
      },
      {
        skill: "SQL",
        difficulty: "EASY",
        questionText: "Which SQL statement retrieves rows from a table?",
        options: ["GET", "SELECT", "FETCH TABLE", "SHOW ROWS"],
        correctIndex: 1,
      },
      {
        skill: "SQL",
        difficulty: "MEDIUM",
        questionText: "What does UNIQUE on a column enforce?",
        options: [
          "Values may repeat freely",
          "All values must be different (NULLs handled by the engine’s rules)",
          "The column becomes a foreign key",
          "The column is encrypted",
        ],
        correctIndex: 1,
      },
      {
        skill: "SQL",
        difficulty: "MEDIUM",
        questionText: "Which JOIN keeps all rows from the left table and matching rows from the right?",
        options: ["INNER JOIN", "LEFT JOIN", "CROSS JOIN", "RIGHT JOIN only on the left"],
        correctIndex: 1,
      },
      {
        skill: "SQL",
        difficulty: "HARD",
        questionText: "What does an index typically improve?",
        options: [
          "Write speed always, never reads",
          "Lookup/filter performance on indexed columns, at some write cost",
          "Network latency to the client",
          "Disk capacity of backups only",
        ],
        correctIndex: 1,
      },
      {
        skill: "Git",
        difficulty: "EASY",
        questionText: "Which command creates a new commit from staged changes?",
        options: ["git add", "git commit", "git pull", "git init"],
        correctIndex: 1,
      },
      {
        skill: "Git",
        difficulty: "MEDIUM",
        questionText: "What does git pull usually do?",
        options: [
          "Only downloads objects without updating branches",
          "Fetches from the remote and integrates into the current branch",
          "Force-pushes local commits",
          "Deletes untracked files",
        ],
        correctIndex: 1,
      },
      {
        skill: "Git",
        difficulty: "HARD",
        questionText: "Why should you avoid rewriting published history (e.g. rebase -f) on a shared main branch?",
        options: [
          "It is slower than merge",
          "Collaborators’ local histories can diverge and cause painful conflicts",
          "Git forbids commits after rebase",
          "Remotes cannot store SHA-1",
        ],
        correctIndex: 1,
      },
      {
        skill: "Communication",
        difficulty: "EASY",
        questionText: "When reporting a blocker to a teammate, which is most effective?",
        options: [
          "Wait until the deadline",
          "State the problem, impact, and what you have already tried",
          "Only mention it in a private note",
          "Assume they already know",
        ],
        correctIndex: 1,
      },
      {
        skill: "Communication",
        difficulty: "MEDIUM",
        questionText: "What is a useful practice in a code review comment?",
        options: [
          "Attack the author personally",
          "Describe the issue, why it matters, and a suggested direction",
          "Request unrelated refactors with no context",
          "Approve without reading",
        ],
        correctIndex: 1,
      },
      {
        skill: "Communication",
        difficulty: "MEDIUM",
        questionText: "How should you handle disagreement in a stand-up?",
        options: [
          "Interrupt until you win",
          "Note the disagreement, park details for a follow-up if it blocks the room",
          "Ignore the other person",
          "Change the project scope immediately",
        ],
        correctIndex: 1,
      },
      {
        skill: "Communication",
        difficulty: "HARD",
        questionText: "When explaining a technical trade-off to a non-engineer stakeholder, you should primarily:",
        options: [
          "Use only jargon and complexity notation",
          "Relate options to risk, time, and user impact in plain language",
          "Refuse to simplify",
          "Send the full git diff only",
        ],
        correctIndex: 1,
      },
    ],
  },
];
