function q(skill, difficulty, questionText, options, correctIndex) {
  return { skill, difficulty, questionText, options, correctIndex };
}

export const FOCUSED_ASSESSMENTS = [
  {
    title: "Java Programming",
    description: "Core Java language, types, collections, and exception handling.",
    questions: [
      q("Java", "EASY", "Which keyword is used to inherit a class in Java?", ["implements", "extends", "inherits", "using"], 1),
      q("Java", "EASY", "What is the default value of an uninitialized boolean instance field?", ["null", "0", "false", "undefined"], 2),
      q("Java", "MEDIUM", "Which collection does not allow duplicate elements?", ["ArrayList", "LinkedList", "HashSet", "Vector"], 2),
      q("Java", "MEDIUM", "What does the finally block do?", ["Runs only on success", "Runs only on exceptions", "Always runs after try/catch unless the JVM exits", "Replaces catch"], 2),
      q("Java", "MEDIUM", "Which statement about String in Java is correct?", ["String is a primitive", "String objects are immutable", "String can be subclassed freely", "String equals uses identity only"], 1),
      q("Java", "HARD", "What is the time complexity of HashMap.get in the typical case?", ["O(n)", "O(log n)", "O(1)", "O(n log n)"], 2),
      q("Java", "HARD", "Checked exceptions in Java must be…", ["Ignored", "Declared or caught", "Wrapped as Errors", "Logged only"], 1),
      q("Java", "MEDIUM", "Which access modifier makes a member visible only within the same package (default)?", ["public", "protected", "private", "no modifier (package-private)"], 3),
    ],
  },
  {
    title: "OOP Fundamentals",
    description: "Encapsulation, inheritance, polymorphism, and abstraction.",
    questions: [
      q("OOP", "EASY", "Encapsulation primarily means…", ["Hiding implementation behind well-defined interfaces", "Using many threads", "Avoiding functions", "Storing data in files"], 0),
      q("OOP", "EASY", "Polymorphism allows…", ["One interface, many implementations", "Only one class per file", "Global variables", "Circular inheritance"], 0),
      q("OOP", "MEDIUM", "Which is an example of abstraction?", ["Exposing every field as public", "Defining an interface for payment without showing gateway details", "Copy-pasting methods", "Using goto"], 1),
      q("OOP", "MEDIUM", "Overriding occurs when…", ["Two methods in the same class share a name and different parameters", "A subclass provides a new implementation of a superclass method", "A field is renamed", "A class is made final"], 1),
      q("OOP", "MEDIUM", "Composition is preferred over inheritance when…", ["You need a strict is-a hierarchy", "You want to reuse behavior via has-a relationships", "The language forbids interfaces", "You need multiple return types"], 1),
      q("OOP", "HARD", "The Liskov Substitution Principle requires that…", ["Subtypes can replace base types without breaking callers", "Every class has a singleton", "Fields are always private", "Methods never throw"], 0),
      q("OOP", "HARD", "A pure abstract type with no implementation is typically called…", ["A struct", "An interface / protocol", "A mixin field", "A daemon"], 1),
      q("OOP", "EASY", "Which access level best supports encapsulation of internals?", ["public fields", "private fields with controlled methods", "global statics", "package-wide mutable arrays"], 1),
    ],
  },
  {
    title: "DSA",
    description: "Arrays, hashing, trees, graphs, and complexity for coding interviews.",
    questions: [
      q("DSA", "EASY", "Binary search on a sorted array is typically…", ["O(n)", "O(log n)", "O(n²)", "O(1) always"], 1),
      q("DSA", "EASY", "A stack is…", ["FIFO", "LIFO", "Priority-only", "Random access"], 1),
      q("DSA", "MEDIUM", "BFS on an unweighted graph commonly uses a…", ["Stack", "Queue", "Only a heap", "AVL tree"], 1),
      q("DSA", "MEDIUM", "Worst-case search in an unbalanced BST is…", ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 2),
      q("DSA", "MEDIUM", "A hash table’s average-case lookup is…", ["O(n)", "O(1)", "O(n²)", "O(log log n)"], 1),
      q("DSA", "HARD", "Dijkstra’s algorithm (binary heap) on a sparse graph is about…", ["O(V²)", "O((V+E) log V)", "O(E²)", "O(V)"], 1),
      q("DSA", "HARD", "Which structure is best for a min-priority queue?", ["Queue", "Heap", "Singly linked list only", "Hash set"], 1),
      q("DSA", "MEDIUM", "Stable sorting preserves…", ["Memory locality only", "Relative order of equal keys", "Worst-case O(n)", "In-place requirement"], 1),
    ],
  },
  {
    title: "SQL Fundamentals",
    description: "SELECT, joins, aggregation, and constraints used in product databases.",
    questions: [
      q("SQL", "EASY", "Which clause filters groups after aggregation?", ["WHERE", "HAVING", "FROM", "ORDER BY"], 1),
      q("SQL", "EASY", "INNER JOIN returns rows that…", ["Exist in the left table only", "Match in both tables", "Exist in the right table only", "Are always cartesian"], 1),
      q("SQL", "MEDIUM", "A PRIMARY KEY must be…", ["Nullable and unique", "Unique and not null", "A float", "A trigger"], 1),
      q("SQL", "MEDIUM", "LEFT JOIN keeps…", ["Only matching rows", "All left rows, matching right or NULL", "All right rows only", "No unmatched rows"], 1),
      q("SQL", "MEDIUM", "COUNT(*) counts…", ["Non-null expressions only", "All rows in the group", "Distinct keys only", "Indexes"], 1),
      q("SQL", "HARD", "A transaction that is isolated from dirty reads at least uses…", ["READ UNCOMMITTED only", "A level that prevents dirty reads (e.g. READ COMMITTED+)", "No locks ever", "DDL only"], 1),
      q("SQL", "HARD", "An index on (user_id, created_at) is most useful for…", ["SELECT * without filters", "Filters/sorts that start with user_id", "Only full table scans", "Updating every column"], 1),
      q("SQL", "MEDIUM", "FOREIGN KEY enforces…", ["Column types", "Referential integrity to another table", "JSON shape", "Network access"], 1),
    ],
  },
  {
    title: "Spring Boot",
    description: "Spring Boot services, dependency injection, and REST controllers.",
    questions: [
      q("Spring Boot", "EASY", "The main Spring Boot entry typically uses…", ["@SpringBootApplication", "@Entity", "@Autowired on the class only", "@Table"], 0),
      q("Spring Boot", "EASY", "application.properties / application.yml is used for…", ["Only logging", "Externalized configuration", "SQL migrations exclusively", "Frontend bundling"], 1),
      q("Spring Boot", "MEDIUM", "@RestController combines…", ["@Controller and @ResponseBody", "@Entity and @Service", "@Bean and @Config", "@Async and @Scheduled"], 0),
      q("Spring Boot", "MEDIUM", "Constructor injection is preferred because…", ["It hides dependencies", "It makes required dependencies explicit and easier to test", "It disables IoC", "It requires field reflection"], 1),
      q("Spring Boot", "MEDIUM", "Spring Data JPA repositories typically…", ["Require JDBC boilerplate", "Declare query methods or @Query", "Replace the database", "Run only native C"], 1),
      q("Spring Boot", "HARD", "@Transactional defaults to rollback on…", ["Checked exceptions only", "Unchecked runtime exceptions", "All HTTP 200s", "Successful commits"], 1),
      q("Spring Boot", "HARD", "Actuator is used for…", ["UI theming", "Production-ready health and metrics endpoints", "ORM only", "CSS"], 1),
      q("Spring Boot", "MEDIUM", "Which annotation maps HTTP GET?", ["@PostMapping", "@GetMapping", "@DeleteEntity", "@PatchBean"], 1),
    ],
  },
  {
    title: "Git",
    description: "Commits, branches, merge vs rebase, and collaboration workflow.",
    questions: [
      q("Git", "EASY", "git clone copies…", ["Only the latest file", "A repository including history (by default)", "SSH keys", "The database"], 1),
      q("Git", "EASY", "git status shows…", ["Remote-only tags", "Working tree and staging state", "JVM threads", "SQL locks"], 1),
      q("Git", "MEDIUM", "A detached HEAD means…", ["HEAD points at a commit, not a branch name", "The repo has no remotes", "The index is locked", "Credentials expired"], 0),
      q("Git", "MEDIUM", "git merge combines histories by…", ["Always rewriting all SHAs", "Creating a merge commit (unless fast-forward)", "Deleting branches", "Squashing remotes only"], 1),
      q("Git", "MEDIUM", "git rebase typically…", ["Replays commits onto another base", "Deletes the remote", "Creates orphan tags", "Disables hooks"], 0),
      q("Git", "HARD", "force-pushing a rewritten shared branch is risky because…", ["It compresses objects", "It can overwrite collaborators’ commits", "It upgrades TLS", "It disables fetch"], 1),
      q("Git", "HARD", "A pull request / merge request is…", ["A Git object type required by core", "A hosting workflow to review before integrating a branch", "A rebase flag", "A tag format"], 1),
      q("Git", "MEDIUM", "gitignore excludes files from…", ["Being committed when untracked (matching patterns)", "Existing remotes automatically", "All history retroactively by default", "SSH"], 0),
    ],
  },
  {
    title: "Python Programming",
    description: "Python syntax, data types, functions, and common standard-library patterns.",
    questions: [
      q("Python", "EASY", "Which creates a dictionary?", ["[1, 2]", "{'a': 1}", "{1, 2}", "(1,) only as a list"], 1),
      q("Python", "EASY", "list.append(x) …", ["Returns a new list", "Mutates the list in place", "Is O(n) always at the front", "Sorts the list"], 1),
      q("Python", "MEDIUM", "A list comprehension [x for x in xs if x] is closest to…", ["A map then filter", "A reduce only", "A class decorator", "A metaclass"], 0),
      q("Python", "MEDIUM", "The GIL in CPython primarily affects…", ["Disk encoding", "CPU-bound multi-threading in one process", "JSON keys", "pip versions"], 1),
      q("Python", "MEDIUM", "with open(path) as f: ensures…", ["Async only", "The file is closed via the context manager", "UTF-32", "Network pooling"], 1),
      q("Python", "HARD", "*args vs **kwargs…", ["*args is keyword-only", "*args collects positional extras; **kwargs collects named extras", "They are identical", "They disable typing"], 1),
      q("Python", "HARD", "A generator uses…", ["return only", "yield to produce a lazy iterator", "goto", "malloc"], 1),
      q("Python", "MEDIUM", "isinstance(x, list) checks…", ["Variable names", "Runtime type against list (or subclass)", "Import graphs", "Syntax only"], 1),
    ],
  },
  {
    title: "React",
    description: "Components, hooks, keys, and effects in modern React.",
    questions: [
      q("React", "EASY", "State that depends on previous state should use…", ["setCount(count + 1) only", "setCount((prev) => prev + 1)", "count++ in render", "this.state"], 1),
      q("React", "EASY", "JSX must return…", ["Multiple adjacent elements without a parent or fragment", "A single parent or fragment", "A class only", "A CSS file"], 1),
      q("React", "MEDIUM", "useEffect dependencies should include…", ["Nothing ever", "Values the effect reads from props/state", "Only numbers", "Window"], 1),
      q("React", "MEDIUM", "Keys in lists help React…", ["Style items", "Identify which items changed", "Fetch data", "Replace CSS"], 1),
      q("React", "MEDIUM", "Lifting state up means…", ["Using Redux only", "Moving shared state to a common parent", "Inline styles", "Refs for all inputs"], 1),
      q("React", "HARD", "A stale closure in a hook usually means…", ["The function captured old state/props", "The DOM is XML", "CSS modules failed", "HTTPS expired"], 0),
      q("React", "HARD", "useMemo is for…", ["Skipping expensive recalculation when deps are unchanged", "Replacing useState", "Network caching in the browser cache API", "CSS-in-JS"], 0),
      q("React", "MEDIUM", "Controlled inputs take value from…", ["The DOM only", "React state (or props) plus onChange", "localStorage only", "Cookies"], 1),
    ],
  },
  {
    title: "Node.js and REST APIs",
    description: "Node.js runtime, Express-style routing, and REST conventions.",
    questions: [
      q("Node.js", "EASY", "Node.js is primarily…", ["A browser engine", "A JavaScript runtime built on V8", "A SQL database", "A CSS preprocessor"], 1),
      q("Node.js", "MEDIUM", "The event loop lets Node…", ["Block on every syscall", "Handle many I/O callbacks without one thread per request", "Replace TCP", "Compile C#"], 1),
      q("Node.js", "MEDIUM", "package.json lists…", ["Only Docker images", "Dependencies and scripts for the project", "Nginx workers", "JVM flags"], 1),
      q("REST APIs", "EASY", "HTTP GET should be…", ["Used to delete resources", "Safe and used to retrieve resources", "Always a file upload", "A WebSocket upgrade"], 1),
      q("REST APIs", "MEDIUM", "A 401 status typically means…", ["Not found", "Unauthorized / authentication required", "Created", "Redirect"], 1),
      q("REST APIs", "MEDIUM", "REST resources are usually identified by…", ["Random cookies only", "URLs (and methods) representing nouns/actions", "CSS classes", "Git tags"], 1),
      q("Node.js", "HARD", "middleware in Express runs…", ["After the response is flushed only", "In order on the request pipeline until a handler ends the cycle", "Only at process exit", "In SQL"], 1),
      q("REST APIs", "HARD", "Idempotent PUT means repeating it…", ["Creates unique rows each time", "Leaves the resource in the same state", "Must use GET", "Requires GraphQL"], 1),
    ],
  },
  {
    title: "Docker and Linux",
    description: "Containers, images, and essential Linux process/file skills.",
    questions: [
      q("Docker", "EASY", "A Docker image is…", ["A running process", "An immutable filesystem snapshot used to start containers", "A VM hypervisor", "A Git branch"], 1),
      q("Docker", "MEDIUM", "docker-compose.yml typically…", ["Defines multi-container applications", "Replaces TCP", "Compiles Java", "Stores JWT secrets in Git by design"], 0),
      q("Docker", "MEDIUM", "A Dockerfile COPY instruction…", ["Runs the container", "Adds files from the build context into the image", "Publishes ports", "Creates volumes at runtime only"], 1),
      q("Linux", "EASY", "ls -l shows…", ["Only hidden files", "Detailed file listing including permissions", "CPU interrupts", "DNS"], 1),
      q("Linux", "MEDIUM", "chmod 755 typically means…", ["Owner rwx, group/others r-x", "No execute", "World writable", "Sticky tmp only"], 0),
      q("Linux", "MEDIUM", "ps / top help you…", ["Compile kernels only", "Inspect running processes", "Format disks", "Edit inodes directly"], 1),
      q("Docker", "HARD", "Bind-mounting a host path into a container…", ["Copies the image layer", "Shares that host directory with the container process", "Disables networking", "Upgrades libc"], 1),
      q("Linux", "HARD", "stderr is conventionally file descriptor…", ["0", "1", "2", "3"], 2),
    ],
  },
  {
    title: "Data Analysis",
    description: "Tables, aggregation, and interpretation skills used in analyst roles.",
    questions: [
      q("Data Analysis", "EASY", "A histogram is best for…", ["Distribution of a numeric variable", "Network topology", "Git blame", "CSS grids"], 0),
      q("Data Analysis", "EASY", "A mean is…", ["The middle value only", "The arithmetic average", "Always the mode", "A join key"], 1),
      q("Data Analysis", "MEDIUM", "Outliers can…", ["Never affect means", "Skew averages; inspect before dropping them", "Only exist in text", "Disable SQL"], 1),
      q("Data Analysis", "MEDIUM", "A join in analysis is used to…", ["Combine related tables on keys", "Encrypt columns", "Render charts", "Train LLMs"], 0),
      q("Data Analysis", "MEDIUM", "Correlation does not prove…", ["Association strength", "Causation", "Direction of a linear relationship", "That two series move together"], 1),
      q("Data Analysis", "HARD", "Train/test leakage is…", ["Using future or target-derived info in features", "A CSS bug", "A Git merge", "A 404"], 0),
      q("Data Analysis", "HARD", "A dashboard should lead with…", ["Every raw row", "The decision question and a few trustworthy metrics", "Unlabeled axes", "Internal IDs only"], 1),
      q("Data Analysis", "MEDIUM", "Missing values should be…", ["Always zero-filled", "Documented and handled (drop, impute, or flag) with justification", "Hidden", "Converted to JSON"], 1),
    ],
  },
];
